[project]
name = "mca"
version = "0.1.0"
description = "A model-agnostic multi-agent conversation framework with centralized turn-based control."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.17.0",
    "pydantic-ai>=0.2.12",
    "python-dotenv>=1.1.0",
]
